//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Scripts/Player/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Player/PlayerActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Level0PlayerActions"",
            ""id"": ""c9f62c5e-e8e9-4b8d-a2ac-cc772afc9705"",
            ""actions"": [
                {
                    ""name"": ""SequenceInputSpace"",
                    ""type"": ""Button"",
                    ""id"": ""dc257db7-5086-4f03-98c2-f60d0d91e835"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SequenceInputW"",
                    ""type"": ""Button"",
                    ""id"": ""d50dac87-9abc-4ea4-81ae-3d9f6b8ce090"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SequenceInputA"",
                    ""type"": ""Button"",
                    ""id"": ""97425b92-f07b-44ae-85f6-d26be5184cb3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SequenceInputS"",
                    ""type"": ""Button"",
                    ""id"": ""2ff00f1c-b332-4b7d-b643-cccac1a807e7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SequenceInputD"",
                    ""type"": ""Button"",
                    ""id"": ""6b2fa440-55d7-47be-bbfc-1c298d6e9719"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bdf53888-e084-4389-a4de-52c7eda56729"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SequenceInputSpace"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d91c73f-857a-4864-9955-7448780ff5ca"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SequenceInputW"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a654f95e-8a7a-48de-a394-c8c6596182d4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SequenceInputA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7aac5c2-225b-44e5-99c2-a55c136e80fb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SequenceInputS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e35436d-e6ad-4e86-8085-5bed600f9458"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SequenceInputD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Level3PlayerActions"",
            ""id"": ""a033d367-4e68-4f94-a02e-37eac565e8e1"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""8f320dde-0030-4b4f-97c7-e831b0fce698"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""1da55081-e1ab-464f-b540-c0646cce83f1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pulse"",
                    ""type"": ""Button"",
                    ""id"": ""3f8e5c4a-9d2b-4e1c-8a7f-6b3e9c1d5f2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""f72c67c9-ce27-4db8-b9b4-fa2b68b7adbc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""82620896-6387-4315-b013-8c785ee65cce"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""40889ec1-daac-40e1-a29a-409bb9d5c2b8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e33f60a8-775e-471a-8327-f63c70f1257e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2e333aa4-af0f-4862-b0d9-6594be4df1bb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4ca34641-a7f0-4ec9-bca7-9d218ca200a8"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a2c5d8f-1b3e-4f9a-8c6d-2e4f7b9a1c3e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pulse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Level0PlayerActions
        m_Level0PlayerActions = asset.FindActionMap("Level0PlayerActions", throwIfNotFound: true);
        m_Level0PlayerActions_SequenceInputSpace = m_Level0PlayerActions.FindAction("SequenceInputSpace", throwIfNotFound: true);
        m_Level0PlayerActions_SequenceInputW = m_Level0PlayerActions.FindAction("SequenceInputW", throwIfNotFound: true);
        m_Level0PlayerActions_SequenceInputA = m_Level0PlayerActions.FindAction("SequenceInputA", throwIfNotFound: true);
        m_Level0PlayerActions_SequenceInputS = m_Level0PlayerActions.FindAction("SequenceInputS", throwIfNotFound: true);
        m_Level0PlayerActions_SequenceInputD = m_Level0PlayerActions.FindAction("SequenceInputD", throwIfNotFound: true);
        // Level3PlayerActions
        m_Level3PlayerActions = asset.FindActionMap("Level3PlayerActions", throwIfNotFound: true);
        m_Level3PlayerActions_Move = m_Level3PlayerActions.FindAction("Move", throwIfNotFound: true);
        m_Level3PlayerActions_Look = m_Level3PlayerActions.FindAction("Look", throwIfNotFound: true);
        m_Level3PlayerActions_Pulse = m_Level3PlayerActions.FindAction("Pulse", throwIfNotFound: true);
    }

    ~@PlayerActions()
    {
        UnityEngine.Debug.Assert(!m_Level0PlayerActions.enabled, "This will cause a leak and performance issues, PlayerActions.Level0PlayerActions.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Level3PlayerActions.enabled, "This will cause a leak and performance issues, PlayerActions.Level3PlayerActions.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Level0PlayerActions
    private readonly InputActionMap m_Level0PlayerActions;
    private List<ILevel0PlayerActionsActions> m_Level0PlayerActionsActionsCallbackInterfaces = new List<ILevel0PlayerActionsActions>();
    private readonly InputAction m_Level0PlayerActions_SequenceInputSpace;
    private readonly InputAction m_Level0PlayerActions_SequenceInputW;
    private readonly InputAction m_Level0PlayerActions_SequenceInputA;
    private readonly InputAction m_Level0PlayerActions_SequenceInputS;
    private readonly InputAction m_Level0PlayerActions_SequenceInputD;
    /// <summary>
    /// Provides access to input actions defined in input action map "Level0PlayerActions".
    /// </summary>
    public struct Level0PlayerActionsActions
    {
        private @PlayerActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Level0PlayerActionsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Level0PlayerActions/SequenceInputSpace".
        /// </summary>
        public InputAction @SequenceInputSpace => m_Wrapper.m_Level0PlayerActions_SequenceInputSpace;
        /// <summary>
        /// Provides access to the underlying input action "Level0PlayerActions/SequenceInputW".
        /// </summary>
        public InputAction @SequenceInputW => m_Wrapper.m_Level0PlayerActions_SequenceInputW;
        /// <summary>
        /// Provides access to the underlying input action "Level0PlayerActions/SequenceInputA".
        /// </summary>
        public InputAction @SequenceInputA => m_Wrapper.m_Level0PlayerActions_SequenceInputA;
        /// <summary>
        /// Provides access to the underlying input action "Level0PlayerActions/SequenceInputS".
        /// </summary>
        public InputAction @SequenceInputS => m_Wrapper.m_Level0PlayerActions_SequenceInputS;
        /// <summary>
        /// Provides access to the underlying input action "Level0PlayerActions/SequenceInputD".
        /// </summary>
        public InputAction @SequenceInputD => m_Wrapper.m_Level0PlayerActions_SequenceInputD;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Level0PlayerActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Level0PlayerActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Level0PlayerActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Level0PlayerActionsActions" />
        public void AddCallbacks(ILevel0PlayerActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_Level0PlayerActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Level0PlayerActionsActionsCallbackInterfaces.Add(instance);
            @SequenceInputSpace.started += instance.OnSequenceInputSpace;
            @SequenceInputSpace.performed += instance.OnSequenceInputSpace;
            @SequenceInputSpace.canceled += instance.OnSequenceInputSpace;
            @SequenceInputW.started += instance.OnSequenceInputW;
            @SequenceInputW.performed += instance.OnSequenceInputW;
            @SequenceInputW.canceled += instance.OnSequenceInputW;
            @SequenceInputA.started += instance.OnSequenceInputA;
            @SequenceInputA.performed += instance.OnSequenceInputA;
            @SequenceInputA.canceled += instance.OnSequenceInputA;
            @SequenceInputS.started += instance.OnSequenceInputS;
            @SequenceInputS.performed += instance.OnSequenceInputS;
            @SequenceInputS.canceled += instance.OnSequenceInputS;
            @SequenceInputD.started += instance.OnSequenceInputD;
            @SequenceInputD.performed += instance.OnSequenceInputD;
            @SequenceInputD.canceled += instance.OnSequenceInputD;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Level0PlayerActionsActions" />
        private void UnregisterCallbacks(ILevel0PlayerActionsActions instance)
        {
            @SequenceInputSpace.started -= instance.OnSequenceInputSpace;
            @SequenceInputSpace.performed -= instance.OnSequenceInputSpace;
            @SequenceInputSpace.canceled -= instance.OnSequenceInputSpace;
            @SequenceInputW.started -= instance.OnSequenceInputW;
            @SequenceInputW.performed -= instance.OnSequenceInputW;
            @SequenceInputW.canceled -= instance.OnSequenceInputW;
            @SequenceInputA.started -= instance.OnSequenceInputA;
            @SequenceInputA.performed -= instance.OnSequenceInputA;
            @SequenceInputA.canceled -= instance.OnSequenceInputA;
            @SequenceInputS.started -= instance.OnSequenceInputS;
            @SequenceInputS.performed -= instance.OnSequenceInputS;
            @SequenceInputS.canceled -= instance.OnSequenceInputS;
            @SequenceInputD.started -= instance.OnSequenceInputD;
            @SequenceInputD.performed -= instance.OnSequenceInputD;
            @SequenceInputD.canceled -= instance.OnSequenceInputD;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Level0PlayerActionsActions.UnregisterCallbacks(ILevel0PlayerActionsActions)" />.
        /// </summary>
        /// <seealso cref="Level0PlayerActionsActions.UnregisterCallbacks(ILevel0PlayerActionsActions)" />
        public void RemoveCallbacks(ILevel0PlayerActionsActions instance)
        {
            if (m_Wrapper.m_Level0PlayerActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Level0PlayerActionsActions.AddCallbacks(ILevel0PlayerActionsActions)" />
        /// <seealso cref="Level0PlayerActionsActions.RemoveCallbacks(ILevel0PlayerActionsActions)" />
        /// <seealso cref="Level0PlayerActionsActions.UnregisterCallbacks(ILevel0PlayerActionsActions)" />
        public void SetCallbacks(ILevel0PlayerActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_Level0PlayerActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Level0PlayerActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Level0PlayerActionsActions" /> instance referencing this action map.
    /// </summary>
    public Level0PlayerActionsActions @Level0PlayerActions => new Level0PlayerActionsActions(this);

    // Level3PlayerActions
    private readonly InputActionMap m_Level3PlayerActions;
    private List<ILevel3PlayerActionsActions> m_Level3PlayerActionsActionsCallbackInterfaces = new List<ILevel3PlayerActionsActions>();
    private readonly InputAction m_Level3PlayerActions_Move;
    private readonly InputAction m_Level3PlayerActions_Look;
    private readonly InputAction m_Level3PlayerActions_Pulse;
    /// <summary>
    /// Provides access to input actions defined in input action map "Level3PlayerActions".
    /// </summary>
    public struct Level3PlayerActionsActions
    {
        private @PlayerActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Level3PlayerActionsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Level3PlayerActions/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Level3PlayerActions_Move;
        /// <summary>
        /// Provides access to the underlying input action "Level3PlayerActions/Look".
        /// </summary>
        public InputAction @Look => m_Wrapper.m_Level3PlayerActions_Look;
        /// <summary>
        /// Provides access to the underlying input action "Level3PlayerActions/Pulse".
        /// </summary>
        public InputAction @Pulse => m_Wrapper.m_Level3PlayerActions_Pulse;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Level3PlayerActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Level3PlayerActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Level3PlayerActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Level3PlayerActionsActions" />
        public void AddCallbacks(ILevel3PlayerActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_Level3PlayerActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Level3PlayerActionsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Pulse.started += instance.OnPulse;
            @Pulse.performed += instance.OnPulse;
            @Pulse.canceled += instance.OnPulse;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Level3PlayerActionsActions" />
        private void UnregisterCallbacks(ILevel3PlayerActionsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Pulse.started -= instance.OnPulse;
            @Pulse.performed -= instance.OnPulse;
            @Pulse.canceled -= instance.OnPulse;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Level3PlayerActionsActions.UnregisterCallbacks(ILevel3PlayerActionsActions)" />.
        /// </summary>
        /// <seealso cref="Level3PlayerActionsActions.UnregisterCallbacks(ILevel3PlayerActionsActions)" />
        public void RemoveCallbacks(ILevel3PlayerActionsActions instance)
        {
            if (m_Wrapper.m_Level3PlayerActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Level3PlayerActionsActions.AddCallbacks(ILevel3PlayerActionsActions)" />
        /// <seealso cref="Level3PlayerActionsActions.RemoveCallbacks(ILevel3PlayerActionsActions)" />
        /// <seealso cref="Level3PlayerActionsActions.UnregisterCallbacks(ILevel3PlayerActionsActions)" />
        public void SetCallbacks(ILevel3PlayerActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_Level3PlayerActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Level3PlayerActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Level3PlayerActionsActions" /> instance referencing this action map.
    /// </summary>
    public Level3PlayerActionsActions @Level3PlayerActions => new Level3PlayerActionsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Level0PlayerActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Level0PlayerActionsActions.AddCallbacks(ILevel0PlayerActionsActions)" />
    /// <seealso cref="Level0PlayerActionsActions.RemoveCallbacks(ILevel0PlayerActionsActions)" />
    public interface ILevel0PlayerActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "SequenceInputSpace" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSequenceInputSpace(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SequenceInputW" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSequenceInputW(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SequenceInputA" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSequenceInputA(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SequenceInputS" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSequenceInputS(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SequenceInputD" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSequenceInputD(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Level3PlayerActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Level3PlayerActionsActions.AddCallbacks(ILevel3PlayerActionsActions)" />
    /// <seealso cref="Level3PlayerActionsActions.RemoveCallbacks(ILevel3PlayerActionsActions)" />
    public interface ILevel3PlayerActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLook(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Pulse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPulse(InputAction.CallbackContext context);
    }
}
