//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Scripts/Player/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Player/PlayerActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Level0PlayerActions"",
            ""id"": ""c9f62c5e-e8e9-4b8d-a2ac-cc772afc9705"",
            ""actions"": [
                {
                    ""name"": ""SequenceInputSpace"",
                    ""type"": ""Button"",
                    ""id"": ""dc257db7-5086-4f03-98c2-f60d0d91e835"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SequenceInputW"",
                    ""type"": ""Button"",
                    ""id"": ""d50dac87-9abc-4ea4-81ae-3d9f6b8ce090"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SequenceInputA"",
                    ""type"": ""Button"",
                    ""id"": ""97425b92-f07b-44ae-85f6-d26be5184cb3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SequenceInputS"",
                    ""type"": ""Button"",
                    ""id"": ""2ff00f1c-b332-4b7d-b643-cccac1a807e7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SequenceInputD"",
                    ""type"": ""Button"",
                    ""id"": ""6b2fa440-55d7-47be-bbfc-1c298d6e9719"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bdf53888-e084-4389-a4de-52c7eda56729"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SequenceInputSpace"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d91c73f-857a-4864-9955-7448780ff5ca"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SequenceInputW"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a654f95e-8a7a-48de-a394-c8c6596182d4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SequenceInputA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7aac5c2-225b-44e5-99c2-a55c136e80fb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SequenceInputS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e35436d-e6ad-4e86-8085-5bed600f9458"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SequenceInputD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Level7PlayerActions"",
            ""id"": ""c22c1d7f-f2ef-4d75-8177-da423f781651"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""60fbbc95-a889-43ed-ab9f-c015173b09dc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""e456c361-1224-488e-8d8b-ea4ccbd39b93"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""03fc6765-4430-4dc5-a134-c9251e60c2ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f772a16f-4042-419f-bf12-e12b67328dff"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use"",
                    ""type"": ""Button"",
                    ""id"": ""ff53bd75-4385-4b2d-aeb1-3e52d2b2a9a0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""284c789c-5184-4634-9065-3a6fe2ad1e66"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6801e244-a87f-4123-93b3-a7133590c9a8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3e772d2e-0141-4a2f-8208-d0c8feebea2d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0865819d-798f-494a-9c6c-de54ffa6ba5b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""02e0a1f1-daa3-4f2d-a42d-e8925ec196d0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5a94a637-74ef-44a4-abe8-9326c4803c46"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a4ce3510-0b54-40f4-8c45-aa1aaf1beefe"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ce6c8ffb-beb9-4550-a895-0312b2fd98be"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0ea467fe-31fb-4a60-a6d3-d1a058b62f5a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5e40efca-87ef-413f-a8f9-b3b07c80ceea"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cebd71e-f0a5-4133-a5c1-6a76479ba266"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false),StickDeadzone,ScaleVector2(x=300,y=300)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7c0f27e-d661-4bfe-812b-f71b2f6df5f9"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=5),InvertVector2(invertX=false)"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f9e6149-c1de-4acc-93c3-6543ed3859a8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b27533b1-ea09-48fd-8f9f-34ccca093e6d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bedaffe-56b9-4f27-82aa-bea3a76246bd"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a851076-e558-47da-b3b4-6e5fc54a05fc"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f40be198-4bc8-476f-9adc-29c1edf7f3d0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Level3PlayerActions"",
            ""id"": ""a033d367-4e68-4f94-a02e-37eac565e8e1"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""8f320dde-0030-4b4f-97c7-e831b0fce698"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""1da55081-e1ab-464f-b540-c0646cce83f1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pulse"",
                    ""type"": ""Button"",
                    ""id"": ""3f8e5c4a-9d2b-4e1c-8a7f-6b3e9c1d5f2a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""f72c67c9-ce27-4db8-b9b4-fa2b68b7adbc"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""82620896-6387-4315-b013-8c785ee65cce"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""40889ec1-daac-40e1-a29a-409bb9d5c2b8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e33f60a8-775e-471a-8327-f63c70f1257e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2e333aa4-af0f-4862-b0d9-6594be4df1bb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4ca34641-a7f0-4ec9-bca7-9d218ca200a8"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a2c5d8f-1b3e-4f9a-8c6d-2e4f7b9a1c3e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pulse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Level4PlayerActions"",
            ""id"": ""ca302bc5-3fd4-4fda-a5df-2a52d6b75a7d"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""9eb77ed4-1bfe-4c16-8e56-ee911009c077"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Use"",
                    ""type"": ""Button"",
                    ""id"": ""af61c852-7a42-4f52-8b33-d0e7b06917d9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6ab57dd9-3320-4142-97a2-5eb2eb20cabc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""AD"",
                    ""id"": ""c9e85fa5-35e0-4af3-a4fd-2351c9da0ef0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a7941ce0-e357-4a1b-89bd-55efbe1097a4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ebb278a9-5cb4-461d-8c8e-1919dbfd8e4a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""17cd8f4f-bf7d-4ea7-9f8d-ac509e0a59bf"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2aadb54-0385-4399-b644-80e6ce40d0e3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Level4PlayerActionsNew"",
            ""id"": ""1e77cf91-cbe6-48da-aeeb-8853656ca543"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""12bef45e-add8-416b-866e-3902145de07c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""0651930e-0900-403d-9a44-956a93ea498a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""1b03bc1b-74de-4347-90f7-d17398803741"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d56dff43-7890-4a19-84af-de84503bc248"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use"",
                    ""type"": ""Button"",
                    ""id"": ""b5136f59-314f-4575-92ac-f5f6e187080c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""88aaaeae-d7b8-4f06-ba33-2b6fa3161069"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7d5b0101-fd92-43b3-bb78-a8f6cf9e06bf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""86a9e020-8462-4750-9022-9eb2b77c5a63"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""382c5016-17bd-4a69-92dd-647741a29ee9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""793aa799-30f3-4ca6-ad78-4fb6edf1fbad"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""108f1293-bf6c-4cf7-87dd-33c7f39461be"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c59fe9be-bb0d-44ec-a082-e9cc60c4dcb5"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""98cb4e34-e7f1-47d8-a5ac-b8f9c02033f2"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b928166d-3a47-459e-9ccd-99f74bc693d8"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0b879d86-0cab-4281-b07d-62684569e153"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40a1fb84-fe7f-46cf-8026-1df6374dd002"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false),StickDeadzone,ScaleVector2(x=300,y=300)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bd1a977-24f8-4755-8034-6ce2ad73252b"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=2,y=2),InvertVector2(invertX=false)"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8eebe3a6-ed5e-4072-a21d-7a060116ea58"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6eb9b28a-d23a-435a-b6be-241254e30a99"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2893acb-1845-4554-9ff3-c0c02da9be86"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ce5860d-8aa1-4f76-ac40-b03e86cd1d7c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d498b49-03ef-40cf-8115-b3d0117236f2"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Level0PlayerActions
        m_Level0PlayerActions = asset.FindActionMap("Level0PlayerActions", throwIfNotFound: true);
        m_Level0PlayerActions_SequenceInputSpace = m_Level0PlayerActions.FindAction("SequenceInputSpace", throwIfNotFound: true);
        m_Level0PlayerActions_SequenceInputW = m_Level0PlayerActions.FindAction("SequenceInputW", throwIfNotFound: true);
        m_Level0PlayerActions_SequenceInputA = m_Level0PlayerActions.FindAction("SequenceInputA", throwIfNotFound: true);
        m_Level0PlayerActions_SequenceInputS = m_Level0PlayerActions.FindAction("SequenceInputS", throwIfNotFound: true);
        m_Level0PlayerActions_SequenceInputD = m_Level0PlayerActions.FindAction("SequenceInputD", throwIfNotFound: true);
        // Level7PlayerActions
        m_Level7PlayerActions = asset.FindActionMap("Level7PlayerActions", throwIfNotFound: true);
        m_Level7PlayerActions_Move = m_Level7PlayerActions.FindAction("Move", throwIfNotFound: true);
        m_Level7PlayerActions_Look = m_Level7PlayerActions.FindAction("Look", throwIfNotFound: true);
        m_Level7PlayerActions_Jump = m_Level7PlayerActions.FindAction("Jump", throwIfNotFound: true);
        m_Level7PlayerActions_Sprint = m_Level7PlayerActions.FindAction("Sprint", throwIfNotFound: true);
        m_Level7PlayerActions_Use = m_Level7PlayerActions.FindAction("Use", throwIfNotFound: true);
        // Level3PlayerActions
        m_Level3PlayerActions = asset.FindActionMap("Level3PlayerActions", throwIfNotFound: true);
        m_Level3PlayerActions_Move = m_Level3PlayerActions.FindAction("Move", throwIfNotFound: true);
        m_Level3PlayerActions_Look = m_Level3PlayerActions.FindAction("Look", throwIfNotFound: true);
        m_Level3PlayerActions_Pulse = m_Level3PlayerActions.FindAction("Pulse", throwIfNotFound: true);
        // Level4PlayerActions
        m_Level4PlayerActions = asset.FindActionMap("Level4PlayerActions", throwIfNotFound: true);
        m_Level4PlayerActions_Move = m_Level4PlayerActions.FindAction("Move", throwIfNotFound: true);
        m_Level4PlayerActions_Use = m_Level4PlayerActions.FindAction("Use", throwIfNotFound: true);
        m_Level4PlayerActions_Jump = m_Level4PlayerActions.FindAction("Jump", throwIfNotFound: true);
        // Level4PlayerActionsNew
        m_Level4PlayerActionsNew = asset.FindActionMap("Level4PlayerActionsNew", throwIfNotFound: true);
        m_Level4PlayerActionsNew_Move = m_Level4PlayerActionsNew.FindAction("Move", throwIfNotFound: true);
        m_Level4PlayerActionsNew_Look = m_Level4PlayerActionsNew.FindAction("Look", throwIfNotFound: true);
        m_Level4PlayerActionsNew_Jump = m_Level4PlayerActionsNew.FindAction("Jump", throwIfNotFound: true);
        m_Level4PlayerActionsNew_Sprint = m_Level4PlayerActionsNew.FindAction("Sprint", throwIfNotFound: true);
        m_Level4PlayerActionsNew_Use = m_Level4PlayerActionsNew.FindAction("Use", throwIfNotFound: true);
    }

    ~@PlayerActions()
    {
        UnityEngine.Debug.Assert(!m_Level0PlayerActions.enabled, "This will cause a leak and performance issues, PlayerActions.Level0PlayerActions.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Level7PlayerActions.enabled, "This will cause a leak and performance issues, PlayerActions.Level7PlayerActions.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Level3PlayerActions.enabled, "This will cause a leak and performance issues, PlayerActions.Level3PlayerActions.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Level4PlayerActions.enabled, "This will cause a leak and performance issues, PlayerActions.Level4PlayerActions.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Level4PlayerActionsNew.enabled, "This will cause a leak and performance issues, PlayerActions.Level4PlayerActionsNew.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Level0PlayerActions
    private readonly InputActionMap m_Level0PlayerActions;
    private List<ILevel0PlayerActionsActions> m_Level0PlayerActionsActionsCallbackInterfaces = new List<ILevel0PlayerActionsActions>();
    private readonly InputAction m_Level0PlayerActions_SequenceInputSpace;
    private readonly InputAction m_Level0PlayerActions_SequenceInputW;
    private readonly InputAction m_Level0PlayerActions_SequenceInputA;
    private readonly InputAction m_Level0PlayerActions_SequenceInputS;
    private readonly InputAction m_Level0PlayerActions_SequenceInputD;
    /// <summary>
    /// Provides access to input actions defined in input action map "Level0PlayerActions".
    /// </summary>
    public struct Level0PlayerActionsActions
    {
        private @PlayerActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Level0PlayerActionsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Level0PlayerActions/SequenceInputSpace".
        /// </summary>
        public InputAction @SequenceInputSpace => m_Wrapper.m_Level0PlayerActions_SequenceInputSpace;
        /// <summary>
        /// Provides access to the underlying input action "Level0PlayerActions/SequenceInputW".
        /// </summary>
        public InputAction @SequenceInputW => m_Wrapper.m_Level0PlayerActions_SequenceInputW;
        /// <summary>
        /// Provides access to the underlying input action "Level0PlayerActions/SequenceInputA".
        /// </summary>
        public InputAction @SequenceInputA => m_Wrapper.m_Level0PlayerActions_SequenceInputA;
        /// <summary>
        /// Provides access to the underlying input action "Level0PlayerActions/SequenceInputS".
        /// </summary>
        public InputAction @SequenceInputS => m_Wrapper.m_Level0PlayerActions_SequenceInputS;
        /// <summary>
        /// Provides access to the underlying input action "Level0PlayerActions/SequenceInputD".
        /// </summary>
        public InputAction @SequenceInputD => m_Wrapper.m_Level0PlayerActions_SequenceInputD;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Level0PlayerActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Level0PlayerActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Level0PlayerActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Level0PlayerActionsActions" />
        public void AddCallbacks(ILevel0PlayerActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_Level0PlayerActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Level0PlayerActionsActionsCallbackInterfaces.Add(instance);
            @SequenceInputSpace.started += instance.OnSequenceInputSpace;
            @SequenceInputSpace.performed += instance.OnSequenceInputSpace;
            @SequenceInputSpace.canceled += instance.OnSequenceInputSpace;
            @SequenceInputW.started += instance.OnSequenceInputW;
            @SequenceInputW.performed += instance.OnSequenceInputW;
            @SequenceInputW.canceled += instance.OnSequenceInputW;
            @SequenceInputA.started += instance.OnSequenceInputA;
            @SequenceInputA.performed += instance.OnSequenceInputA;
            @SequenceInputA.canceled += instance.OnSequenceInputA;
            @SequenceInputS.started += instance.OnSequenceInputS;
            @SequenceInputS.performed += instance.OnSequenceInputS;
            @SequenceInputS.canceled += instance.OnSequenceInputS;
            @SequenceInputD.started += instance.OnSequenceInputD;
            @SequenceInputD.performed += instance.OnSequenceInputD;
            @SequenceInputD.canceled += instance.OnSequenceInputD;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Level0PlayerActionsActions" />
        private void UnregisterCallbacks(ILevel0PlayerActionsActions instance)
        {
            @SequenceInputSpace.started -= instance.OnSequenceInputSpace;
            @SequenceInputSpace.performed -= instance.OnSequenceInputSpace;
            @SequenceInputSpace.canceled -= instance.OnSequenceInputSpace;
            @SequenceInputW.started -= instance.OnSequenceInputW;
            @SequenceInputW.performed -= instance.OnSequenceInputW;
            @SequenceInputW.canceled -= instance.OnSequenceInputW;
            @SequenceInputA.started -= instance.OnSequenceInputA;
            @SequenceInputA.performed -= instance.OnSequenceInputA;
            @SequenceInputA.canceled -= instance.OnSequenceInputA;
            @SequenceInputS.started -= instance.OnSequenceInputS;
            @SequenceInputS.performed -= instance.OnSequenceInputS;
            @SequenceInputS.canceled -= instance.OnSequenceInputS;
            @SequenceInputD.started -= instance.OnSequenceInputD;
            @SequenceInputD.performed -= instance.OnSequenceInputD;
            @SequenceInputD.canceled -= instance.OnSequenceInputD;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Level0PlayerActionsActions.UnregisterCallbacks(ILevel0PlayerActionsActions)" />.
        /// </summary>
        /// <seealso cref="Level0PlayerActionsActions.UnregisterCallbacks(ILevel0PlayerActionsActions)" />
        public void RemoveCallbacks(ILevel0PlayerActionsActions instance)
        {
            if (m_Wrapper.m_Level0PlayerActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Level0PlayerActionsActions.AddCallbacks(ILevel0PlayerActionsActions)" />
        /// <seealso cref="Level0PlayerActionsActions.RemoveCallbacks(ILevel0PlayerActionsActions)" />
        /// <seealso cref="Level0PlayerActionsActions.UnregisterCallbacks(ILevel0PlayerActionsActions)" />
        public void SetCallbacks(ILevel0PlayerActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_Level0PlayerActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Level0PlayerActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Level0PlayerActionsActions" /> instance referencing this action map.
    /// </summary>
    public Level0PlayerActionsActions @Level0PlayerActions => new Level0PlayerActionsActions(this);

    // Level7PlayerActions
    private readonly InputActionMap m_Level7PlayerActions;
    private List<ILevel7PlayerActionsActions> m_Level7PlayerActionsActionsCallbackInterfaces = new List<ILevel7PlayerActionsActions>();
    private readonly InputAction m_Level7PlayerActions_Move;
    private readonly InputAction m_Level7PlayerActions_Look;
    private readonly InputAction m_Level7PlayerActions_Jump;
    private readonly InputAction m_Level7PlayerActions_Sprint;
    private readonly InputAction m_Level7PlayerActions_Use;
    /// <summary>
    /// Provides access to input actions defined in input action map "Level7PlayerActions".
    /// </summary>
    public struct Level7PlayerActionsActions
    {
        private @PlayerActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Level7PlayerActionsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Level7PlayerActions/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Level7PlayerActions_Move;
        /// <summary>
        /// Provides access to the underlying input action "Level7PlayerActions/Look".
        /// </summary>
        public InputAction @Look => m_Wrapper.m_Level7PlayerActions_Look;
        /// <summary>
        /// Provides access to the underlying input action "Level7PlayerActions/Jump".
        /// </summary>
        public InputAction @Jump => m_Wrapper.m_Level7PlayerActions_Jump;
        /// <summary>
        /// Provides access to the underlying input action "Level7PlayerActions/Sprint".
        /// </summary>
        public InputAction @Sprint => m_Wrapper.m_Level7PlayerActions_Sprint;
        /// <summary>
        /// Provides access to the underlying input action "Level7PlayerActions/Use".
        /// </summary>
        public InputAction @Use => m_Wrapper.m_Level7PlayerActions_Use;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Level7PlayerActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Level7PlayerActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Level7PlayerActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Level7PlayerActionsActions" />
        public void AddCallbacks(ILevel7PlayerActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_Level7PlayerActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Level7PlayerActionsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Use.started += instance.OnUse;
            @Use.performed += instance.OnUse;
            @Use.canceled += instance.OnUse;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Level7PlayerActionsActions" />
        private void UnregisterCallbacks(ILevel7PlayerActionsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Use.started -= instance.OnUse;
            @Use.performed -= instance.OnUse;
            @Use.canceled -= instance.OnUse;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Level7PlayerActionsActions.UnregisterCallbacks(ILevel7PlayerActionsActions)" />.
        /// </summary>
        /// <seealso cref="Level7PlayerActionsActions.UnregisterCallbacks(ILevel7PlayerActionsActions)" />
        public void RemoveCallbacks(ILevel7PlayerActionsActions instance)
        {
            if (m_Wrapper.m_Level7PlayerActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Level7PlayerActionsActions.AddCallbacks(ILevel7PlayerActionsActions)" />
        /// <seealso cref="Level7PlayerActionsActions.RemoveCallbacks(ILevel7PlayerActionsActions)" />
        /// <seealso cref="Level7PlayerActionsActions.UnregisterCallbacks(ILevel7PlayerActionsActions)" />
        public void SetCallbacks(ILevel7PlayerActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_Level7PlayerActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Level7PlayerActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Level7PlayerActionsActions" /> instance referencing this action map.
    /// </summary>
    public Level7PlayerActionsActions @Level7PlayerActions => new Level7PlayerActionsActions(this);

    // Level3PlayerActions
    private readonly InputActionMap m_Level3PlayerActions;
    private List<ILevel3PlayerActionsActions> m_Level3PlayerActionsActionsCallbackInterfaces = new List<ILevel3PlayerActionsActions>();
    private readonly InputAction m_Level3PlayerActions_Move;
    private readonly InputAction m_Level3PlayerActions_Look;
    private readonly InputAction m_Level3PlayerActions_Pulse;
    /// <summary>
    /// Provides access to input actions defined in input action map "Level3PlayerActions".
    /// </summary>
    public struct Level3PlayerActionsActions
    {
        private @PlayerActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Level3PlayerActionsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Level3PlayerActions/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Level3PlayerActions_Move;
        /// <summary>
        /// Provides access to the underlying input action "Level3PlayerActions/Look".
        /// </summary>
        public InputAction @Look => m_Wrapper.m_Level3PlayerActions_Look;
        /// <summary>
        /// Provides access to the underlying input action "Level3PlayerActions/Pulse".
        /// </summary>
        public InputAction @Pulse => m_Wrapper.m_Level3PlayerActions_Pulse;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Level3PlayerActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Level3PlayerActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Level3PlayerActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Level3PlayerActionsActions" />
        public void AddCallbacks(ILevel3PlayerActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_Level3PlayerActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Level3PlayerActionsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Pulse.started += instance.OnPulse;
            @Pulse.performed += instance.OnPulse;
            @Pulse.canceled += instance.OnPulse;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Level3PlayerActionsActions" />
        private void UnregisterCallbacks(ILevel3PlayerActionsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Pulse.started -= instance.OnPulse;
            @Pulse.performed -= instance.OnPulse;
            @Pulse.canceled -= instance.OnPulse;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Level3PlayerActionsActions.UnregisterCallbacks(ILevel3PlayerActionsActions)" />.
        /// </summary>
        /// <seealso cref="Level3PlayerActionsActions.UnregisterCallbacks(ILevel3PlayerActionsActions)" />
        public void RemoveCallbacks(ILevel3PlayerActionsActions instance)
        {
            if (m_Wrapper.m_Level3PlayerActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Level3PlayerActionsActions.AddCallbacks(ILevel3PlayerActionsActions)" />
        /// <seealso cref="Level3PlayerActionsActions.RemoveCallbacks(ILevel3PlayerActionsActions)" />
        /// <seealso cref="Level3PlayerActionsActions.UnregisterCallbacks(ILevel3PlayerActionsActions)" />
        public void SetCallbacks(ILevel3PlayerActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_Level3PlayerActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Level3PlayerActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Level3PlayerActionsActions" /> instance referencing this action map.
    /// </summary>
    public Level3PlayerActionsActions @Level3PlayerActions => new Level3PlayerActionsActions(this);

    // Level4PlayerActions
    private readonly InputActionMap m_Level4PlayerActions;
    private List<ILevel4PlayerActionsActions> m_Level4PlayerActionsActionsCallbackInterfaces = new List<ILevel4PlayerActionsActions>();
    private readonly InputAction m_Level4PlayerActions_Move;
    private readonly InputAction m_Level4PlayerActions_Use;
    private readonly InputAction m_Level4PlayerActions_Jump;
    /// <summary>
    /// Provides access to input actions defined in input action map "Level4PlayerActions".
    /// </summary>
    public struct Level4PlayerActionsActions
    {
        private @PlayerActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Level4PlayerActionsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Level4PlayerActions/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Level4PlayerActions_Move;
        /// <summary>
        /// Provides access to the underlying input action "Level4PlayerActions/Use".
        /// </summary>
        public InputAction @Use => m_Wrapper.m_Level4PlayerActions_Use;
        /// <summary>
        /// Provides access to the underlying input action "Level4PlayerActions/Jump".
        /// </summary>
        public InputAction @Jump => m_Wrapper.m_Level4PlayerActions_Jump;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Level4PlayerActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Level4PlayerActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Level4PlayerActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Level4PlayerActionsActions" />
        public void AddCallbacks(ILevel4PlayerActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_Level4PlayerActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Level4PlayerActionsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Use.started += instance.OnUse;
            @Use.performed += instance.OnUse;
            @Use.canceled += instance.OnUse;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Level4PlayerActionsActions" />
        private void UnregisterCallbacks(ILevel4PlayerActionsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Use.started -= instance.OnUse;
            @Use.performed -= instance.OnUse;
            @Use.canceled -= instance.OnUse;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Level4PlayerActionsActions.UnregisterCallbacks(ILevel4PlayerActionsActions)" />.
        /// </summary>
        /// <seealso cref="Level4PlayerActionsActions.UnregisterCallbacks(ILevel4PlayerActionsActions)" />
        public void RemoveCallbacks(ILevel4PlayerActionsActions instance)
        {
            if (m_Wrapper.m_Level4PlayerActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Level4PlayerActionsActions.AddCallbacks(ILevel4PlayerActionsActions)" />
        /// <seealso cref="Level4PlayerActionsActions.RemoveCallbacks(ILevel4PlayerActionsActions)" />
        /// <seealso cref="Level4PlayerActionsActions.UnregisterCallbacks(ILevel4PlayerActionsActions)" />
        public void SetCallbacks(ILevel4PlayerActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_Level4PlayerActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Level4PlayerActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Level4PlayerActionsActions" /> instance referencing this action map.
    /// </summary>
    public Level4PlayerActionsActions @Level4PlayerActions => new Level4PlayerActionsActions(this);

    // Level4PlayerActionsNew
    private readonly InputActionMap m_Level4PlayerActionsNew;
    private List<ILevel4PlayerActionsNewActions> m_Level4PlayerActionsNewActionsCallbackInterfaces = new List<ILevel4PlayerActionsNewActions>();
    private readonly InputAction m_Level4PlayerActionsNew_Move;
    private readonly InputAction m_Level4PlayerActionsNew_Look;
    private readonly InputAction m_Level4PlayerActionsNew_Jump;
    private readonly InputAction m_Level4PlayerActionsNew_Sprint;
    private readonly InputAction m_Level4PlayerActionsNew_Use;
    /// <summary>
    /// Provides access to input actions defined in input action map "Level4PlayerActionsNew".
    /// </summary>
    public struct Level4PlayerActionsNewActions
    {
        private @PlayerActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Level4PlayerActionsNewActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Level4PlayerActionsNew/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Level4PlayerActionsNew_Move;
        /// <summary>
        /// Provides access to the underlying input action "Level4PlayerActionsNew/Look".
        /// </summary>
        public InputAction @Look => m_Wrapper.m_Level4PlayerActionsNew_Look;
        /// <summary>
        /// Provides access to the underlying input action "Level4PlayerActionsNew/Jump".
        /// </summary>
        public InputAction @Jump => m_Wrapper.m_Level4PlayerActionsNew_Jump;
        /// <summary>
        /// Provides access to the underlying input action "Level4PlayerActionsNew/Sprint".
        /// </summary>
        public InputAction @Sprint => m_Wrapper.m_Level4PlayerActionsNew_Sprint;
        /// <summary>
        /// Provides access to the underlying input action "Level4PlayerActionsNew/Use".
        /// </summary>
        public InputAction @Use => m_Wrapper.m_Level4PlayerActionsNew_Use;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Level4PlayerActionsNew; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Level4PlayerActionsNewActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Level4PlayerActionsNewActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Level4PlayerActionsNewActions" />
        public void AddCallbacks(ILevel4PlayerActionsNewActions instance)
        {
            if (instance == null || m_Wrapper.m_Level4PlayerActionsNewActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Level4PlayerActionsNewActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Use.started += instance.OnUse;
            @Use.performed += instance.OnUse;
            @Use.canceled += instance.OnUse;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Level4PlayerActionsNewActions" />
        private void UnregisterCallbacks(ILevel4PlayerActionsNewActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Use.started -= instance.OnUse;
            @Use.performed -= instance.OnUse;
            @Use.canceled -= instance.OnUse;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Level4PlayerActionsNewActions.UnregisterCallbacks(ILevel4PlayerActionsNewActions)" />.
        /// </summary>
        /// <seealso cref="Level4PlayerActionsNewActions.UnregisterCallbacks(ILevel4PlayerActionsNewActions)" />
        public void RemoveCallbacks(ILevel4PlayerActionsNewActions instance)
        {
            if (m_Wrapper.m_Level4PlayerActionsNewActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Level4PlayerActionsNewActions.AddCallbacks(ILevel4PlayerActionsNewActions)" />
        /// <seealso cref="Level4PlayerActionsNewActions.RemoveCallbacks(ILevel4PlayerActionsNewActions)" />
        /// <seealso cref="Level4PlayerActionsNewActions.UnregisterCallbacks(ILevel4PlayerActionsNewActions)" />
        public void SetCallbacks(ILevel4PlayerActionsNewActions instance)
        {
            foreach (var item in m_Wrapper.m_Level4PlayerActionsNewActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Level4PlayerActionsNewActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Level4PlayerActionsNewActions" /> instance referencing this action map.
    /// </summary>
    public Level4PlayerActionsNewActions @Level4PlayerActionsNew => new Level4PlayerActionsNewActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Level0PlayerActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Level0PlayerActionsActions.AddCallbacks(ILevel0PlayerActionsActions)" />
    /// <seealso cref="Level0PlayerActionsActions.RemoveCallbacks(ILevel0PlayerActionsActions)" />
    public interface ILevel0PlayerActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "SequenceInputSpace" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSequenceInputSpace(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SequenceInputW" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSequenceInputW(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SequenceInputA" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSequenceInputA(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SequenceInputS" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSequenceInputS(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SequenceInputD" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSequenceInputD(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Level7PlayerActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Level7PlayerActionsActions.AddCallbacks(ILevel7PlayerActionsActions)" />
    /// <seealso cref="Level7PlayerActionsActions.RemoveCallbacks(ILevel7PlayerActionsActions)" />
    public interface ILevel7PlayerActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLook(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Sprint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSprint(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Use" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUse(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Level3PlayerActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Level3PlayerActionsActions.AddCallbacks(ILevel3PlayerActionsActions)" />
    /// <seealso cref="Level3PlayerActionsActions.RemoveCallbacks(ILevel3PlayerActionsActions)" />
    public interface ILevel3PlayerActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLook(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Pulse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPulse(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Level4PlayerActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Level4PlayerActionsActions.AddCallbacks(ILevel4PlayerActionsActions)" />
    /// <seealso cref="Level4PlayerActionsActions.RemoveCallbacks(ILevel4PlayerActionsActions)" />
    public interface ILevel4PlayerActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Use" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUse(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Level4PlayerActionsNew" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Level4PlayerActionsNewActions.AddCallbacks(ILevel4PlayerActionsNewActions)" />
    /// <seealso cref="Level4PlayerActionsNewActions.RemoveCallbacks(ILevel4PlayerActionsNewActions)" />
    public interface ILevel4PlayerActionsNewActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLook(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Sprint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSprint(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Use" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUse(InputAction.CallbackContext context);
    }
}
